version: "3"

services:

  bern:
    build: .
    ports:
      - 80:8888
    volumes:
      - ./externalData/GNormPlusJava/Dictionary/:/app/GNormPlusJava/Dictionary/
      - ./externalData/tmVarJava/Database:/app/tmVarJava/Database
      - ./externalData/biobert_ner_models?:/app/bern/biobert_ner/
      - ./externalData/data/:/app/normalization/data/
      - ./externalData/resources/:/app/normalization/resources/
    networks:
      - bernnet

networks:
  bernnet:
    driver: bridge