version: "3"

services:

  bern:
    build: .
    ports:
      - 80:8888
    volumes:
      - ./externalData/GNormPlusJava/Dictionary/:/app/GNormPlusJava/Dictionary/
      - ./externalData/tmVarJava/Database:/app/tmVarJava/Database
      - ./externalData/biobert_ner_models/pretrainedBERT:/app/biobert_ner/pretrainedBERT/
      - ./externalData/biobert_ner_models/conf/:/app/biobert_ner/conf/
      - ./externalData/biobert_ner_models/tmp/:/app/biobert_ner/tmp/
      - ./externalData/biobert_ner_models/result/:/app/biobert_ner/result/
      - ./externalData/data/:/app/normalization/data/
      - ./externalData/resources/:/app/normalization/resources/
    networks:
      - bernnet

networks:
  bernnet:
    driver: bridge